/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/agent': typeof AgentRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/config': typeof ConfigRouteWithChildren
  '/contas': typeof ContasRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/tasks': typeof TasksRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/agent': typeof AgentRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/config': typeof ConfigRouteWithChildren
  '/contas': typeof ContasRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/tasks': typeof TasksRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/agent': typeof AgentRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/config': typeof ConfigRouteWithChildren
  '/contas': typeof ContasRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/tasks': typeof TasksRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/agenda'
    | '/agent'
    | '/campanhas'
    | '/config'
    | '/contas'
    | '/credentials'
    | '/dashboard'
    | '/insights'
    | '/logs'
    | '/models'
    | '/tasks'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/agenda'
    | '/agent'
    | '/campanhas'
    | '/config'
    | '/contas'
    | '/credentials'
    | '/dashboard'
    | '/insights'
    | '/logs'
    | '/models'
    | '/tasks'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/agenda'
    | '/agent'
    | '/campanhas'
    | '/config'
    | '/contas'
    | '/credentials'
    | '/dashboard'
    | '/insights'
    | '/logs'
    | '/models'
    | '/tasks'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AgentRoute: typeof AgentRouteWithChildren
  CampanhasRoute: typeof CampanhasRoute
  ConfigRoute: typeof ConfigRouteWithChildren
  ContasRoute: typeof ContasRoute
  CredentialsRoute: typeof CredentialsRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AgentRoute: AgentRouteWithChildren,
  CampanhasRoute: CampanhasRoute,
  ConfigRoute: ConfigRouteWithChildren,
  ContasRoute: ContasRoute,
  CredentialsRoute: CredentialsRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
